name: Build KaChing release zip
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Read version (VERSION file → .toc fallback)
        id: ver
        shell: bash
        run: |
          set -e
          VER=""
          # Prefer VERSION file (e.g., "version": "0.9.9")
          if [ -f VERSION ]; then
            VER=$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' VERSION | head -n1)
          fi
          # Fallback to .toc
          if [ -z "$VER" ] && [ -f KaChing/KaChing.toc ]; then
            VER=$(sed -n 's/^##[[:space:]]*Version:[[:space:]]*\(.*\)$/\1/p' KaChing/KaChing.toc | head -n1)
          fi
          if [ -z "$VER" ] && [ -f KaChing.toc ]; then
            VER=$(sed -n 's/^##[[:space:]]*Version:[[:space:]]*\(.*\)$/\1/p' KaChing.toc | head -n1)
          fi
          [ -z "$VER" ] && VER="0.0.0"
          VER=$(printf '%s' "$VER" | tr -cd '0-9A-Za-z._-')
          echo "ADDON_VER=$VER" >> "$GITHUB_ENV"
          echo "Detected version: $VER"

      - name: Package zip (file has -master; inside folder is KaChing/)
        shell: bash
        run: |
          set -e
          echo "Building KaChing-v${ADDON_VER}-master.zip from $GITHUB_REF_NAME @ $GITHUB_SHA"
          git archive --format=zip --prefix=KaChing/ \
            -o "KaChing-v${ADDON_VER}-master.zip" HEAD
          ls -l

      # If you want the folder inside to be KaChing-master/ instead, swap the step above with:
      # - name: Package zip (file & folder have -master)
      #   run: |
      #     git archive --format=zip --prefix=KaChing-master/ \
      #       -o "KaChing-v${ADDON_VER}-master.zip" HEAD
      #     ls -l

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KaChing-v${{ env.ADDON_VER }}-master.zip
          path: KaChing-v${{ env.ADDON_VER }}-master.zip
